ndtp/android-testify

- .github/workflows/intellij_build.yml
- .github/workflows/intellij_release.yml
- .github/workflows/library_build.yml
- .github/workflows/plugin_build.yml
- .github/workflows/sample_build.yml
- .gitignore
- Plugins/IntelliJ/CHANGELOG.md
- Plugins/IntelliJ/CONTRIBUTING.md
- Plugins/IntelliJ/build.gradle.kts
- Plugins/IntelliJ/gradle.properties
- Plugins/IntelliJ/settings.gradle.kts
- build.gradle
- settings.gradle
Previously the IntelliJ plugin was a separate gradle projected. This PR changes the gradle structure so that the IntelliJ plugin is just another module in the same gradle project graph as all the other modules. The main advantage of this is that it unifies the version number (currently 1.2.0-alpha01) which had previously been using an independent versioning.
- Checkout this branch and run `./gradlew IntelliJ:buildPlugin` from the root
- The built plugin can be found at `/.android-testify/Plugins/IntelliJ/build/libs/IntelliJ-1.2.0-alpha01.jar`
> Unify the IntelliJ plugin version 

- .github/workflows/intellij_build.yml
The `Export Properties` step was not scoping the `gradlew` commands to the `IntelliJ` project so was getting invalid values for the `name` and `version`.
Updated to `IntelliJ:properties`:
```
echo "::set-output name=version::$(./gradlew IntelliJ:properties --console=plain -q | grep "^version:" | cut -f2- -d ' ')"
echo "::set-output name=name::$(./gradlew IntelliJ:properties --console=plain -q | grep "^name:" | cut -f2- -d ' ')"
```
> Export IntelliJ plugin version & name for CI

- Plugins/IntelliJ/build.gradle.kts
- Plugins/IntelliJ/gradle.properties
Should fix the [error](https://github.com/ndtp/android-testify/runs/5996463067?check_suite_focus=true) on `upload-release-asset` currently on `main`
`Error: ENOENT: no such file or directory, stat './plugin-artifact/IntelliJ-1.2.0-alpha01.zip'`
This is caused because the `intellij_build.xml` actions expect the artifact name to be `<project>-<version>.zip` but we were setting the build artifact name to be `<custom project name>-<version>.zip`. So, I removed the `properties("pluginName")` and use the `project.name` instead.
> Use the project name for the IntelliJ build/distributions filename

- .github/workflows/intellij_build.yml
Remove the `[push]` trigger on the `intellij_build` GitHub Action workflow.
> Run the intellij github action workflow on pull_request only

- Library/src/androidTest/java/dev/testify/BitmapCompareTest.kt
- Library/src/androidTest/java/dev/testify/ScreenshotUtilityTest.kt
- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/ScreenshotUtility.kt
- Library/src/main/java/dev/testify/internal/processor/compare/SameAsCompare.kt
- Sample/src/androidTest/java/dev/testify/sample/ScreenshotRuleExampleTests.kt
⚠️ Depends on #27 and #26 
This is Part 3 of 3. 
Resolves #10 
This PR removes the special treatment for the existing capture methods and has them conform to the `CaptureMethod` typealias. `ScreenshotUtility` no longer determines the capture method. Rather, the `CaptureMethod` is now passed in as a parameter and the calling context (in this case, the `ScreenshotRule`) can decide what method to use.
> Issue-10: Refactor existing capture methods to be `CaptureMethod`

- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/report/Reporter.kt
- Library/src/test/java/dev/testify/ReporterTest.kt
Refactor ScreenshotRule to abstract out the configuration from the JUnit4 overrides
This is a preliminary refactoring of `ScreenshotRule` to make its functionality more generic. Eventually, this functionality will be promoted up to a `TestifyCore` class. For now, these changes make the `ScreenshotRule` rely less on `JUnit4` and exposes the configuration and modification methods in a more generic manner.
See https://github.com/ndtp/android-testify/blob/main/docs/architecture/library.md#screenshotextension
No functionality or public API changes. All tests should pass as before.
> Refactor ScreenshotRule to abstract out the configuration from the JUnit4 overrides

- CHANGELOG.md
- Plugins/IntelliJ/CHANGELOG.md
- Plugins/IntelliJ/src/main/kotlin/dev/testify/extensions/ScreenshotClassMarkerProvider.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/extensions/ScreenshotInstrumentationLineMarkerProvider.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/extensions/TooltipProvider.kt
- README.md
- build.gradle
Add support for both new and legacy package names to the IntelliJ plugin.
Resolves #43 
Users will likely take some time to migrate from the `com.shopify` namespace to the new `dev.testify` namespace. During this transition, they may be using newer versions of Android Studio (Dolphin, Electric Eel) which are not supported by the legacy plugin. To facilitate this transition, the plugin can support both new and legacy package names.
1. In any supported version of Android Studio, install the pre-built plugin from [IntelliJ-1.2.0-alpha02.jar.zip](https://github.com/ndtp/android-testify/files/8696361/IntelliJ-1.2.0-alpha02.jar.zip)
1. Open the [current](https://github.com/ndtp/android-testify) `Sample` source code in the preview build of Android Studio.
1. Verify that the 📷 icon is present in …
> Issue-43: IntelliJ plugin supports both new and legacy package names

- .github/workflows/intellij_build.yml
Reverts ndtp/android-testify#39
The `push` trigger is required in order to generate the draft release of the IntelliJ plugin
> Revert "Run the intellij github action workflow on pull_request only"

- Ext/Fullscreen/src/main/java/dev/testify/capture/fullscreen/provider/NavigationBarExclusionRectProvider.kt
- Ext/Fullscreen/src/main/java/dev/testify/capture/fullscreen/provider/StatusBarExclusionRectProvider.kt
- Ext/Fullscreen/src/main/java/dev/testify/capture/fullscreen/provider/SystemUiExclusionRectProvider.kt
- Library/src/androidTest/java/dev/testify/OutputFilePathTest.kt
- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/internal/TestifyConfiguration.kt
- Library/src/main/java/dev/testify/internal/exception/ActivityNotRegisteredException.kt
- Library/src/main/java/dev/testify/internal/exception/ScreenshotBaselineNotDefinedException.kt
- Library/src/main/java/dev/testify/internal/exception/ScreenshotDirectoryNotFoundException.kt
- Library/src/main/java/dev/testify/internal/exception/ScreenshotIsDifferentException.kt
- Library/src/main/java/dev/testify/internal/exception/ViewModificationException.kt
- Library/src/main/java/dev/testify/internal/helpers/OrientationHelper.kt
- Library/src/main/java/dev/testify/internal/modification/FocusModification.kt
- Library/src/main/java/dev/testify/report/ReportSession.kt
- Library/src/main/java/dev/testify/report/Reporter.kt
- Library/src/test/java/dev/testify/ErrorCauseTest.kt
- Library/src/test/java/dev/testify/ReportSessionTest.kt
- Library/src/test/java/dev/testify/ReporterTest.kt
- Library/src/test/java/dev/testify/TestifyFeaturesTest.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/tasks/main/ScreenshotTestTask.kt
- Sample/src/androidTest/java/dev/testify/sample/FullscreenCaptureExampleTests.kt
- Sample/src/androidTest/java/dev/testify/sample/ScreenshotRuleExampleTests.kt
- build.gradle
Creates a `TestifyConfiguration` class which will hold all of the various configuration properties for Testify. This is necessary for two reasons:
1. It will allow reuse of the configuration to new Testify classes that are not based on the ScreenshotRule
2. It reduces the amount of code in ScreenshotRule making it simpler to read and narrowing its purpose.
⚠️  I had to upgrade the ktlint version due to the rules of the old 0.36 version conflicting with the current Android Studio style. That commit inflated the number of lines changed in this PR, but are all style changes.
Created a new `TestifyConfiguration` class and moved the Exclusion Rect properties to it.
<table>
<tr><td>
```kotlin
rule
.defineExclusionRects { rootView, exclusionRects ->
val card = …
```
> Issue-41: Part 2 - Create TestifyConfiguration and move exclusion rects

- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/internal/TestifyConfiguration.kt
- Sample/src/androidTest/java/dev/testify/sample/TestingResourceConfigurationsExampleTest.kt
- Sample/src/androidTest/java/dev/testify/sample/TestingResourceConfigurationsLegacyExampleTest.kt
- Sample/src/androidTest/java/dev/testify/sample/TestingResourcesCounterExampleTest.kt
Move font scale and locale to TestifyConfiguration.
<table>
<tr><td width="600px">
```kotlin
rule
.setLocale(Locale.JAPAN)
.assertSame()
```
</td><td width="600px">
```kotlin
rule
.configure {
locale = Locale.JAPAN
}
.assertSame()
```
</td></tr>
<tr><td width="600px">
```kotlin
rule
.setFontScale(2.0f)
.assertSame()
```
</td><td width="600px">
```kotlin
rule
.configure {
fontScale = 2.0f
}
.assertSame()
```
</td></tr>
</table>
- All tests should pass
> Issue-41: Part 4 - Move font scale and locale to Configuration object

- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/internal/helpers/ActivityProvider.kt
- Library/src/main/java/dev/testify/internal/helpers/OrientationHelper.kt
Provide a generic mechanism for accessing the current Activity
`TestifyConfiguration` should not have access to the Activity, but the `OrientationHelper` needs an Activity.
Rather than pass it through, the current Activity is registered and accessible via the ActivityProvider.
This will be particularly useful when alternatives to the ScreenshotRule (such as a ScreenshotScenario)
are provided.
This is an internal implementation detail and not part of the public API
Tests passing should be sufficient.
> Issue-41: Part 7a - Provide a generic mechanism for accessing the current Activity

- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/internal/TestifyConfiguration.kt
- Library/src/main/java/dev/testify/internal/modification/FocusModification.kt
- Library/src/main/java/dev/testify/internal/modification/HideCursorViewModification.kt
- Library/src/main/java/dev/testify/internal/modification/HidePasswordViewModification.kt
- Library/src/main/java/dev/testify/internal/modification/HideScrollbarsViewModification.kt
- Library/src/main/java/dev/testify/internal/modification/HideTextSuggestionsViewModification.kt
- Library/src/main/java/dev/testify/internal/modification/SoftwareRenderViewModification.kt
- Library/src/main/java/dev/testify/internal/modification/ViewModification.kt
- Sample/src/androidTest/java/dev/testify/sample/ScreenshotRuleExampleTests.kt
- Sample/src/androidTest/java/dev/testify/sample/clients/index/ClientListActivityScreenshotTest.kt
Removes the view modification-related methods from `ScreenshotRule` and replaces them with properties in `TestifyConfiguration`.
<table>
<tr><th colspan=2>Hide scrollbars</th></tr>
<tr><td width="600px">
```kotlin
rule
.setHideScrollbars(true)
.assertSame()
```
</td><td width="600px">
```kotlin
rule
.configure {
hideScrollbars = true
}
.assertSame()
```
</td></tr>
<tr><th colspan=2>Hide passwords</th></tr>
<tr><td width="600px">
```kotlin
rule
.setHidePasswords(true)
.assertSame()
```
</td><td width="600px">
```kotlin
rule
.configure {
hidePasswords = true
}
.assertSame()
```
</td></tr>
<tr><th colspan=2>Hide cursor</th></tr>
<tr><td width="600px">
```kotlin
rule
.setHideCursor(true)
.assertSame()
```
</td><td width="600px">
```kotlin
rule
.configure { …
```
> Issue-41: Part 5 - Move view modifications to TestifyConfiguration

- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/internal/TestifyConfiguration.kt
Remove `setLayoutInspectionModeEnabled` method from `ScreenshotRule` and replace with `pauseForInspection` property in `TestifyConfiguration`
<table>
<tr><td width="600px">
```kotlin
rule
.setLayoutInspectionModeEnabled(true)
.assertSame()
```
</td><td width="600px">
```kotlin
rule
.configure {
pauseForInspection = true
}
.assertSame()
```
</td></tr>
</table>
- Tests should pass
> Issue-41: Part 8 - Move inspection mode to TestifyConfiguration

- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/internal/TestifyConfiguration.kt
- Library/src/main/java/dev/testify/internal/helpers/EspressoHelper.kt
Move Espresso-related functionality to `EspressoHelper` class.
I'd like to reuse the Espresso functionality from the future non-rule-based Testify classes, so I have moved the core Espresso integration into a helper class.
<table>
<tr><td width="600px">
```kotlin
rule
.setHideSoftKeyboard(true)
.assertSame()
```
</td><td width="600px">
```kotlin
rule
.configure {
hideSoftKeyboard = true
}
.assertSame()
```
</td></tr>
</table>
This is mostly an internal implementation change. The only API change is to the `setHideSoftKeyboard` method which is not part of `TestifyConfiguration`
- Tests should pass
> Issue-41: Part 9 - Refactor Espresso functionality into a helper class

- Ext/Accessibility/README.md
- Ext/Accessibility/build.gradle
- Ext/Accessibility/src/main/AndroidManifest.xml
- build.gradle
- settings.gradle
Adds the scaffolding to create a new `:Accessibility` module.
This is just the boilerplate. There is no code yet.
`./gradlew :Accessibility:assembleDebug` to verify that it builds.
> Issue-61: Part 1 - Create accessibility extension module

- .github/workflows/ext_build.yml
- Ext/Accessibility/README.md
- Ext/Compose/src/main/java/dev/testify/ComposableTestActivity.kt
- Ext/Fullscreen/src/main/java/dev/testify/capture/fullscreen/FullscreenCaptureMethod.kt
- Ext/Fullscreen/src/main/java/dev/testify/capture/fullscreen/provider/RealDisplaySize.kt
- build.gradle
<a href="https://search.maven.org/artifact/dev.testify/testify-accessibility"><img alt="Maven Central" src="https://img.shields.io/maven-central/v/dev.testify/testify-accessibility?color=%236e40ed&label=dev.testify%3Atestify-accessibility"/></a>
To help people with disabilities access Android apps, developers of those apps need to consider how their apps will be presented to accessibility services. Some good practices can be checked by automated tools, such as if a View has a contentDescription. Other rules require human judgment, such as whether or not a contentDescription makes sense to all users. Testify Accessibility can be used to verify common errors that lead to a poorly accessible application.
You can combine visual regression testing with accessibility checks to further improve …
> Issue-63: Part 5 - Add README and CI support

- docs/docs/migration.md
- docs/docusaurus.config.js
- docs/src/pages/index.js
Resolves #12 
This PR adds a brief migration guide explaining how to upgrade from the Shopify to dev.testify release.
Future PRs will expand on the migration guide to explain how to move fully to the 2.* architecture.
You can view the rendered migration guide here https://ndtp.github.io/android-testify/
> Issue-12: Add migration documentation

- .github/workflows/sample_build.yml
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- Ext/Accessibility/README.md
- Ext/Compose/README.md
- Ext/Fullscreen/README.md
- README.md
- build.gradle
- test_and_archive.sh
- 2.0.0-alpha01 is the current published version. Updated documents to reflect that.
- 2.0.0-alpha02 is the current working version (and next release). Updated work-in-progress projects to reflect this version.
You can view the rendered changes here https://github.com/ndtp/android-testify/tree/update-versions
> Update documentation to reference 2.0.0-alpha01

- Ext/Compose/src/main/java/dev/testify/ComposableScreenshotRule.kt
- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Sample/src/androidTest/java/dev/testify/sample/compose/ComposableScreenshotTest.kt
Resolves https://github.com/ndtp/android-testify/issues/97
Open the `configure()` method so subclasses can return their own type
> Issue-97: Open the `configure()` method so subclasses can return their own type

- CHANGELOG.md
- Ext/Accessibility/src/main/java/dev/testify/accessibility/internal/BaselineGenerator.kt
- Ext/Fullscreen/src/main/java/dev/testify/capture/fullscreen/FullscreenCaptureMethod.kt
- Library/build.gradle
- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/ScreenshotUtility.kt
- Library/src/main/java/dev/testify/TestifyFeatures.kt
- Library/src/main/java/dev/testify/internal/DeviceIdentifier.kt
- Library/src/main/java/dev/testify/internal/output/OutputFileUtility.kt
- Library/src/main/java/dev/testify/report/Reporter.kt
- Library/src/test/java/dev/testify/DeviceIdentifierTest.kt
- Library/src/test/java/dev/testify/ErrorCauseTest.kt
- Library/src/test/java/dev/testify/ParallelPixelProcessorTest.kt
- Library/src/test/java/dev/testify/RegionCompareTest.kt
- Library/src/test/java/dev/testify/ReportSessionTest.kt
- Library/src/test/java/dev/testify/ReporterTest.kt
- Library/src/test/java/dev/testify/TestifyFeaturesTest.kt
- build.gradle
1. Remove kotlin mockito dependencies
2. Add dependency on mockk
3. Update tests to use mockk
4. Convert `DeviceIdentifier` into top-level functions
Mockito is not able to mock top-level functions and I'm planning to also convert `ScreenshotUtility` and `OutputFileUtility` to top-level functions in a future PR. So, I took the opportunity to swap out Mockito for mockk in this PR.
- All tests should pass
> Switch from kotlin mockito to mockk

- docs/docs/extensions/compose/_category_.json
- docs/docs/extensions/fullscreen/0-overview.md
- docs/docs/extensions/fullscreen/1-setup.md
- docs/docs/extensions/fullscreen/2-test.md
- docs/docs/extensions/fullscreen/_category_.json
Add documentation for the Fullscreen Capture Method extension
1. Checkout the branch `docs-fullscreen`
2. In the `/docs` folder, run `npm start`
3. Verify the documents in the _Extensions_ section
> Add documentation for Fullscreen Capture Method extension

- docs/docs/extensions/accessibility/0-overview.md
- docs/docs/extensions/accessibility/1-setup.md
- docs/docs/extensions/accessibility/2-test.md
- docs/docs/extensions/accessibility/_category_.json
- docs/docs/extensions/compose/_category_.json
Add documentation for Accessibility Checks extension
1. Checkout the branch `docs-accessibility`
2. In the `/docs` folder, run `npm start`
3. Verify the documents in the _Extensions_ section
> Add documentation for Accessibility Checks extension

- Plugins/IntelliJ/CHANGELOG.md
- Plugins/IntelliJ/build.gradle.kts
- Plugins/IntelliJ/gradle.properties
- Plugins/IntelliJ/src/main/kotlin/dev/testify/PsiExtensions.kt
Resolves https://github.com/ndtp/android-testify/issues/127
- Added support for Android Studio Hedgehog | 2023.1.1 Canary 2 | 231.+
- Fix bug parsing nested module names
- Download and install [IntelliJ CE](https://www.jetbrains.com/idea/download), at least version 2020.1.2.
- Open the project in IntelliJ by opening the `./android-testify` directory.
- Open edit configurations to create a new run/debug configuration
- Choose a new `Gradle` configuration
- Name it `Build & Run`
- Ensure that `android-testify/Plugins/IntelliJ` is selected as the `Gradle project`
- Under `Tasks`, enter `buildPlugin runIde`
- You can now use the Run or Debug options
- 
Once you have configured the project as above, you can run the plugin in Android Studio.
The plugin is configured to run Android Studio via …
> Intellij multi module support

- Ext/Accessibility/build.gradle
- Ext/Compose/build.gradle
- Ext/Fullscreen/build.gradle
- Library/build.gradle
- Library/src/androidTest/java/dev/testify/ActivityNotRegisteredExceptionTest.kt
- Library/src/androidTest/java/dev/testify/AssertExpectedDeviceTest.kt
- Library/src/androidTest/java/dev/testify/RuleLifecycleTest.kt
- Library/src/androidTest/java/dev/testify/ScreenshotAnnotationTest.kt
- Library/src/main/java/dev/testify/TestifyFeatures.kt
- Library/src/main/java/dev/testify/internal/extensions/InstrumentationRegistryExtensions.kt
- Library/src/main/java/dev/testify/internal/output/OutputFileUtility.kt
- Plugins/Gradle/build.gradle
- Samples/Legacy/build.gradle
- Samples/Legacy/src/main/java/dev/testify/sample/clients/details/ClientDetailsActivity.kt
- Samples/Legacy/src/main/java/dev/testify/sample/clients/details/edit/ClientDetailsEditActivity.kt
- Samples/Legacy/src/main/res/layout/view_client_details.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- ktlint.gradle
- settings.gradle
Pretty much the idea is to tidy up the gradle scripts and update everything so the project will be able to accommodate a newer sample application. 
- modernize the gradle scripts 
- remove unneeded code from gradle scripts
- update gradle plugin and dependencies
Resolves <issues>
I did it in steps which are visible in the commits. 
1) bump android gradle plugin to 7.4.1 - this required me to change the Plugin project's `sourceCompatability` to Java 11 (this is either fine or very bad)
2) I relocated all of the repository blocks to be in settings.gradle
3) I updated anything that was not current version
Passing CI should be sufficient. 
> Version bumps

- Samples/Flix/src/main/java/dev/testify/samples/flix/domain/model/MovieCreditsDomainModel.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/domain/usecase/LoadHomeScreenUseCase.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/domain/usecase/LoadMovieDetailsUseCase.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/presentation/homescreen/model/HomeScreenPresentationModel.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/presentation/homescreen/viewmodel/HomeScreenViewModel.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/presentation/moviedetails/viewmodel/MovieDetailsViewModel.kt
Enables the network requests to run in parallel drastically speeding up the load times for the main screen and the movie details screen.
Resolves <issues>
By wrapping the network requests in flows, and then using the combine function to collect the flows all at the same time.
Launch the app and ensure the home screen as well as the movie details screen both load correctly.
> Improve the use of Kotlin flows in the two use case classes improving the loading time of the two screens.

- CHANGELOG.md
- Ext/Compose/src/main/java/dev/testify/ComposableScreenshotRule.kt
Exposes the `enableReporter` initializer value from `ScreenshotRule` to the `ComposableScreenshotRule` so this value can be set when configuring a `ComposableScreenshotRule`.
Adds the ability to configure the `enableReporter` value from the `ComposableScreenshotRule` subclass. This initializer value was not accessible before and was hindering us from customizing the `ComposableScreenshotRule` as we wanted. This value is accessible via the superclass `ScreenshotRule` initializer. 
We found that setting `enableReporter` was more reliable than updating the `AndroidManifest` to enable the reporter (per Readme).
I also added documentation for this value based on what I saw around the repo but could use some help to make sure it is accurate. 
Added a new parameter to the …
> Expose ScreenshotRule initializer value to ComposableScreenshotRule

- Samples/Flix/src/main/java/dev/testify/samples/flix/ui/common/composeables/AsynchronousImage.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/ui/common/composeables/CastMember.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/ui/common/composeables/MoviePoster.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/ui/common/composeables/MovieThumbnail.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/ui/homescreen/HomeScreen.kt
Refactors Flix's use of Coil's AsyncImage Composable into a wrapper composable AsynchronousImage. The purpose of this is to isolate our use of AsyncImage such that it would be possible to move to a different image loader, or fix issues we run into. 
Simply created a wrapper composable.
Ensure images in the application continue to be displayed as expected.
> Create simple AsynchronousImage wrapper for Flix

- CHANGELOG.md
- Samples/Flix/build.gradle
- Samples/Flix/src/main/java/dev/testify/samples/flix/application/di/ApplicationModule.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/application/foundation/coil/CoilImageLoader.kt
- Samples/Flix/src/main/java/dev/testify/samples/flix/ui/common/composeables/AsynchronousImage.kt
Fixes flaky tests that were caused by a race condition. Testify would capture its screenshots before the image loading library Coil had completed loading images. Coil loads images asynchronously so this is predicable. This is easily fixed by replacing Coil's coroutine dispatcher with one having Espresso IdlingResource awareness.
https://stackoverflow.com/questions/73044642/how-to-unit-test-if-an-image-was-loaded-using-coil-compose
I reconfigured Coil not to use its factory ImageLoader. I provide a custom ImageLoader that is configured to use the Espresso aware thread pool.
- Ensure the screenshot tests pass for FlixSample
- Ensure the Flix sample app displays images as you would expect.
> FlixSample, repair race condition between screenshot capture and Coil image loading

- Plugins/IntelliJ/CHANGELOG.md
- Plugins/IntelliJ/gradle.properties
Add support to IntelliJ Plugin for Android Studio Iguana | 2023.2.1 Canary 3 | 232.+
> Support Android Studio Iguana | 2023.2.1 Canary 3 | 232.+

- CHANGELOG.md
- Ext/Accessibility/README.md
- Ext/Compose/README.md
- Ext/Fullscreen/README.md
- README.md
- build.gradle
- Android Gradle Plugin to 7.4.1
- Android Material `material` to 1.9.0
- AndroidX `activity-compose` to 1.7.1
- AndroidX `appcompat` to 1.6.1
- AndroidX `core` to 1.10.0
- AndroidX `lifecycle-runtime-ktx` to 2.6.1
- AndroidX Test `espresso-accessibility`, `espresso-core`, `espresso-contrib` to 3.5.1
- AndroidX Test `junit` to 1.1.5
- AndroidX Test `monitor` to 1.6.1
- AndroidX Test `rules` to 1.5.0
- AndroidX Test `runner` to 1.5.2
- Compile SDK to 33
- Dokka to 1.8.10
- Jetpack Compose `compose.ui`, `core`, `material` to 1.4.3
- Jetpack Compose Compile to 1.4.7
- Kotlin to 1.8.21
- `com.android.application` to 7.4.2
- `com.android.library` to 7.4.2
- Internal file management is now abstracted through the new `Destination` interface.
This interface allows for extensibility and …
> Prepare 2.0.0-beta03

- CHANGELOG.md
- Ext/Compose/src/main/java/dev/testify/ComposableScreenshotRule.kt
- Ext/Fullscreen/src/main/java/dev/testify/capture/fullscreen/FullscreenCaptureMethod.kt
- Library/src/androidTest/java/dev/testify/ExperimentalPixelCopyTest.kt
- Library/src/androidTest/java/dev/testify/ScreenshotLifecycleTest.kt
- Library/src/main/java/dev/testify/CompatibilityMethods.kt
- Library/src/main/java/dev/testify/ScreenshotLifecycle.kt
- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/TestifyFeatures.kt
- Library/src/main/java/dev/testify/internal/ConfigurationBuilder.kt
- Library/src/main/java/dev/testify/internal/ScreenshotRuleCompatibilityMethods.kt
- Library/src/main/java/dev/testify/internal/TestifyConfiguration.kt
- Library/src/main/java/dev/testify/internal/helpers/FindRootView.kt
- Library/src/main/java/dev/testify/internal/logic/CompareBitmaps.kt
- Library/src/main/java/dev/testify/internal/logic/TakeScreenshot.kt
- Library/src/test/java/dev/testify/ScreenshotRuleTest.kt
- Samples/Legacy/src/androidTest/java/dev/testify/sample/JavaExampleTest.java
- Samples/Legacy/src/androidTest/java/dev/testify/sample/ScreenshotRuleExampleTests.kt
- Samples/Legacy/src/androidTest/java/dev/testify/sample/compose/ComposeActivityScreenshotTest.kt
Prerequisite for #41 
This PR contributes to the generalization of the Testify Core logic.
1. Extracted `ScreenshotRule.getRootView()` as an extension function `Activity.findRootView()`
2. Migrate `ScreenshotRule.setCaptureMethod()` to a property in `configure {}` (also include backwards compatible helper method)
3. Migrate `ScreenshotRule.setCompareMethod()` to a property in `configure {}` (also include backwards compatible helper method)
This impacts the lifecycle and core code flow for all tests.
Running tests on a variety of configurations would be ideal.
> **Warning**
> 41: Refactor compose method, compare method and findRootView

- CHANGELOG.md
- Ext/Compose/src/main/java/dev/testify/ComposableScreenshotRule.kt
- Library/src/androidTest/java/dev/testify/AssertExpectedDeviceTest.kt
- Library/src/androidTest/java/dev/testify/ScreenshotRuleLifecycleTest.kt
- Library/src/main/java/dev/testify/CompatibilityMethods.kt
- Library/src/main/java/dev/testify/ExtrasProvider.kt
- Library/src/main/java/dev/testify/ScreenshotRule.kt
- Library/src/main/java/dev/testify/ScreenshotUtility.kt
- Library/src/main/java/dev/testify/ViewModification.kt
- Library/src/main/java/dev/testify/ViewProvider.kt
- Library/src/main/java/dev/testify/annotation/AnnotationExtensions.kt
- Library/src/main/java/dev/testify/annotation/TestifyLayout.kt
- Library/src/main/java/dev/testify/internal/ScreenshotRuleCompatibilityMethods.kt
- Library/src/main/java/dev/testify/internal/TestifyConfiguration.kt
- Library/src/main/java/dev/testify/internal/extensions/InstrumentationRegistryExtensions.kt
- Library/src/main/java/dev/testify/internal/helpers/ActivityProvider.kt
- Library/src/main/java/dev/testify/internal/helpers/EspressoHelper.kt
- Library/src/main/java/dev/testify/internal/helpers/IsRunningOnUiThread.kt
- Library/src/main/java/dev/testify/internal/helpers/OutputFileName.kt
- Library/src/main/java/dev/testify/internal/logic/AssertSame.kt
- Library/src/main/java/dev/testify/internal/logic/AssertionState.kt
- Library/src/main/java/dev/testify/internal/logic/InitiliazeView.kt
- Library/src/main/java/dev/testify/internal/logic/ScreenshotLifecycleHost.kt
- Library/src/main/java/dev/testify/internal/logic/TakeScreenshot.kt
- Library/src/main/java/dev/testify/internal/processor/diff/HighContrastDiff.kt
- Library/src/main/java/dev/testify/report/Reporter.kt
- Library/src/test/java/dev/testify/ReporterTest.kt
- Library/src/test/java/dev/testify/ScreenshotRuleTest.kt
- Library/src/test/java/dev/testify/output/DestinationTest.kt
Follow-up to #169 
Resolves #41
This PR completes the refactoring of `ScreenshotRule` into several modules. Specifically, this PR introduces a top-level function version of `assertSame()`. With this, additional screenshot methods can easily be built.
- `ScreenshotRule.getScreenshotInstrumentationAnnotation()` is now a top-level function.
- `Collection<Annotation>.getAnnotation()` renamed to `Collection<Annotation>.findAnnotation()`.
- Package for `getScreenshotAnnotationName()` changed from `dev.testify.internal.extensions` to `dev.testify.annotation`.
- `ScreenshotRule.initializeView()` is now a top-level function.
- `EspressoHelper` now extends `ScreenshotLifecycle` and `beforeScreenshot()` has been replaced with `afterInitializeView()`
- `isRunningOnUiThread()` added as a top-level …
> 41: Refactor assertSame() to be a top-level function

- CHANGELOG.md
- Ext/Compose/src/main/java/dev/testify/ComposableScreenshotRule.kt
Fixed a bug in ComposableScreenshotRule.setCaptureMethod() where it was incorrectly ignoring the passed in captureMethod argument.
> setCaptureMethod was ignoring the passed-in argument value for captureMethod

- Plugins/IntelliJ/README.md
- Plugins/IntelliJ/gradle.properties
- Plugins/IntelliJ/src/main/kotlin/dev/testify/ConfirmationDialogWrapper.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/actions/screenshot/BaseScreenshotAction.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/actions/utility/BaseFileAction.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/extensions/ScreenshotClassMarkerProvider.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/extensions/ScreenshotInstrumentationLineMarkerProvider.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/extensions/TooltipProvider.kt
- Plugins/IntelliJ/src/main/resources/META-INF/plugin.xml
- README.md
- docs/docs/get-started/7-set-up-intellij-plugin.md
Resolves #204 
- Bump version to 2.1.0
- Added support for Android Studio Jellyfish | 2023.3.1 Canary 10 | 233.+
- Replaced deprecated API calls.
- Dropped support for Android Studio versions 221.* and earlier (Electric Eel, Dolphin, Chipmunk, Bumblebee)
1. Download and install Jellyfish https://developer.android.com/studio/preview
1. Check out this branch `ISSUE-204-jellyfish_support`
1. Change to the Plugins/Intellij directory
1. Edit the [`ideDir` in the `build.gradle.kts`](https://github.com/ndtp/android-testify/blob/main/Plugins/IntelliJ/build.gradle.kts#L62) file to point to your installed copy of Jellyfish
1. Run `./gradlew buildPlugin runIde`
1. Verify that the Testify plugin works correctly with any `@ScreenshotInstrumentation` tests
- 2.1.0 has been submitted to the JetBrains …
> 204: Added support for Android Studio Jellyfish | 2023.3.1 Canary 10 | 233.+

- Plugins/IntelliJ/gradle.properties
Resolves #210 
* Bump version to 2.2.0
* Added support for Android Studio Koala | 2024.1.1 Canary 6
1. Download and install Koala https://developer.android.com/studio/preview
2. Check out this branch `ISSUE-210-Koala_support`
3. Change to the Plugins/Intellij directory
4. Edit the [`ideDir` in the `build.gradle.kts`](https://github.com/ndtp/android-testify/blob/main/Plugins/IntelliJ/build.gradle.kts#L62) file to point to your installed copy of Jellyfish
5. Run `./gradlew buildPlugin runIde`
6. Verify that the Testify plugin works correctly with any `@ScreenshotInstrumentation` tests
> 210: Added support for Android Studio Koala | 2024.1.1 Canary 6

- CHANGELOG.md
- Library/src/androidTest/java/dev/testify/core/processor/BitmapExtensionsTest.kt
- Library/src/main/AndroidManifest.xml
- Library/src/main/java/dev/testify/core/logic/AssertSame.kt
- Library/src/main/java/dev/testify/core/processor/BitmapExtentions.kt
- Library/src/main/java/dev/testify/core/processor/ParallelPixelProcessor.kt
- Library/src/main/java/dev/testify/core/processor/compare/FuzzyCompare.kt
- Library/src/main/java/dev/testify/core/processor/diff/HighContrastDiff.kt
- Library/src/main/java/dev/testify/internal/helpers/ManifestHelpers.kt
- Library/src/main/res/values/strings.xml
- Library/src/test/java/dev/testify/ScreenshotRuleTest.kt
- Library/src/test/java/dev/testify/core/processor/ParallelPixelProcessorTest.kt
- Library/src/test/java/dev/testify/core/processor/compare/FuzzyCompareTest.kt
- Library/src/test/java/dev/testify/core/processor/compare/RegionCompareTest.kt
- Library/src/test/java/dev/testify/core/processor/diff/HighContrastDiffTest.kt
- Library/src/test/java/dev/testify/scenario/ScreenshotScenarioRuleTest.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/TestifyExtension.kt
- Samples/Flix/FlixLibrary/build.gradle
- Samples/Flix/build.gradle
- Samples/Legacy/build.gradle
- build.gradle
- Add `parallelThreads` extension property to the Gradle plugin. This allows for customization of the number of worker threads to be used by the ParallelProcessor. Set limits on the thread pool to a minimum of 1 and a maximum of 4.
- Refactor the ParallelPixelProcessor and introduce a new configuration class to wrap the thread configuration variables and the CoroutineDispatcher configuration.
- Several small improvements to the FuzzyCompare method to perform fewer allocations inside the analyze function
- Upgrade UiAutomator dependency to 2.3.0 https://developer.android.com/jetpack/androidx/releases/test-uiautomator
- Recycle the bitmaps in the finalize block of `assertSame()`
- Add several new tests and enhancements to the existing ParallelProcessor tests
- Upgrade the compile SDK for …
> Bug fixes and performance improvements for the ParallelPixelProcessor

- CHANGELOG.md
- Ext/Accessibility/README.md
- Ext/Compose/README.md
- Ext/Fullscreen/README.md
- Library/src/androidTest/java/dev/testify/core/processor/ImageBufferTest.kt
- Library/src/main/java/dev/testify/core/exception/ImageBufferAllocationException.kt
- Library/src/main/java/dev/testify/core/exception/LowMemoryException.kt
- Library/src/main/java/dev/testify/core/processor/ImageBuffer.kt
- Library/src/main/java/dev/testify/core/processor/ParallelPixelProcessor.kt
- Library/src/test/java/dev/testify/core/exception/ErrorCauseTest.kt
- Library/src/test/java/dev/testify/core/processor/ParallelPixelProcessorTest.kt
- Library/src/test/java/dev/testify/core/processor/compare/FuzzyCompareTest.kt
- Library/src/test/java/dev/testify/core/processor/compare/RegionCompareTest.kt
- Library/src/test/java/dev/testify/core/processor/diff/HighContrastDiffTest.kt
- Plugins/Gradle/README.md
- README.md
- Samples/Legacy/src/androidTest/java/dev/testify/sample/ScreenshotRuleExampleTests.kt
- build.gradle
- docs/docs/extensions/accessibility/1-setup.md
- docs/docs/extensions/compose/1-setup.md
- docs/docs/extensions/fullscreen/1-setup.md
- docs/docs/get-started/1-setup.md
- docs/docusaurus.config.js
- gradle.properties
Parallel pixel processing requires the allocation of two byte buffers. For a typical device resolution of 1080 x 1920, two buffers of approximately 2 MB each (4 MB total) are allocated. 
Most AVDs are configured with a heap size of 25% their available RAM. For example, 512 MB for a device with 2 GB of RAM. See: https://android.googlesource.com/platform/external/qemu/+/emu-master-dev/android/android-emu/android/main-common.c#1292 
This is normally more than sufficient for parallel pixel processing. However, in some instances it has been observed where the heap size for androidTest instrumentation runners is set to only 16 MB, which is not sufficient for Testify. If you encounter this exception, please verify that your emulator is correctly configured with at least 2 GB of RAM.
Testify will …
> Improve handling of memory allocations and OOM errors

- Plugins/IntelliJ/gradle.properties
- Plugins/IntelliJ/src/main/kotlin/dev/testify/PsiExtensions.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/actions/utility/BaseFileAction.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/actions/utility/BaseUtilityAction.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/actions/utility/DeleteBaselineAction.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/actions/utility/GoToBaselineAction.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/actions/utility/GoToSourceAction.kt
- Plugins/IntelliJ/src/main/kotlin/dev/testify/extensions/ScreenshotClassMarkerProvider.kt
- Plugins/IntelliJ/src/main/resources/META-INF/plugin.xml
1. Added a `Go To Source` popup menu item to baseline image asset files. This action will navigate you from the PNG baseline image to the test source code.
https://github.com/user-attachments/assets/1d7c8ec8-b38b-47e6-b30f-29a9642682f4
2. Added a `Baseline Image` destination in the `Go To` popup menu when right-clicking on the test source code. This action will navigate you to the baseline image for the current test.
https://github.com/user-attachments/assets/4c7a4618-02b7-4831-9131-94ed8b12bbb0
1. You can check out this branch and run the `buildPlugin runIde` tasks
2. Or, you can install the following plugin: 
[IntelliJ-2.3.0.zip](https://github.com/user-attachments/files/16229400/IntelliJ-2.3.0.zip)
> Intellij Plugin: Add "Go To Source" and "Go To Baseline Image" actions

- .github/workflows/central_release.yml
- Plugins/IntelliJ/CHANGELOG.md
- Plugins/IntelliJ/gradle.properties
- Plugins/IntelliJ/src/main/resources/META-INF/plugin.xml
Resolves https://github.com/ndtp/android-testify/issues/233
Release 2.4.0 with added support for Android Studio Ladybug | 2024.2.1 Canary 9 | 242.+
> [!WARNING]
> 233: Added support for Android Studio Ladybug | 2024.2.1 Canary 9 | 242.+ to IntelliJ plugin

- .gitignore
- CHANGELOG.md
- Plugins/Gradle/src/main/kotlin/dev/testify/TestifyPlugin.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/internal/Adb.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/internal/ClientUtilities.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/internal/DeviceUtilities.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/tasks/internal/TestifyDefaultTask.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/tasks/main/ScreenshotClearTask.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/tasks/main/ScreenshotPullTask.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/tasks/main/ScreenshotTestTask.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/tasks/report/ReportPullTask.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/tasks/report/ReportShowTask.kt
- Plugins/Gradle/src/main/kotlin/dev/testify/tasks/utility/SettingsTask.kt
- Plugins/Gradle/src/test/kotlin/dev/testify/internal/AdbTest.kt
- Plugins/Gradle/src/test/kotlin/dev/testify/test/BaseTest.kt
Resolves https://github.com/ndtp/android-testify/issues/203
Alternative take on https://github.com/ndtp/android-testify/pull/235
Uses Gradle's StyledTextOutput to format log output, allowing us to respect console mode and console color configuration.
Since Testify is a plugin, I think it makes more sense to integrate with Gradle itself than `NO_COLOR`.
Supported styles are:
1. `./gradlew FlixLibrary:testifySettings -Pverbose=true` shows coloured output
2. `./gradlew FlixLibrary:testifySettings -Pverbose=true --console=plain` shows no coloured output
3. ` ./gradlew -Dorg.gradle.color.description=BLUE FlixLibrary:testifySettings -Pverbose=true --console=plain` shows customizing colour output
> [!WARNING]
> This change must keep `main` in a shippable state; **it may be shipped without …
> 203: Use Gradle's StyledTextOutput for log formatting

- Plugins/IntelliJ/CHANGELOG.md
- Plugins/IntelliJ/build.gradle.kts
- Plugins/IntelliJ/gradle.properties
- Plugins/IntelliJ/src/main/resources/META-INF/plugin.xml
Resolves #241 
Declare support for Android Studio Meerkat | 2024.3.1 Canary 7 | 243.+
1. Download and install [Android Studio Meerkat](https://developer.android.com/studio/preview)
2. Update the [`ideDir`](https://github.com/ndtp/android-testify/blob/main/Plugins/IntelliJ/build.gradle.kts#L63) to point to your installation from (1)
3. From the `Plugins/IntelliJ` directory, run `./gradlew buildPlugin runIde`
> [!WARNING]
> 241: Support Android Studio Meerkat | 2024.3.1 Canary 7 | 243.+

- CHANGELOG.md
- Samples/Gmd/README.md
Resolves #250
Copy corrected documentation from the [blog post](http://localhost:3000/android-testify/blog/gradle-managed-device) to the GMD README.
Note: Requires #249 
> [!WARNING]
> 250: Correct error in GMD documentation

- CHANGELOG.md
- Library/src/androidTest/java/dev/testify/BitmapCompareTest.kt
- Library/src/androidTest/java/dev/testify/FuzzyCompareBitmapTest.kt
- Library/src/androidTest/java/dev/testify/ScreenshotUtilityTest.kt
- Library/src/main/java/dev/testify/ScreenshotUtility.kt
- Library/src/main/java/dev/testify/core/AssertExpectedDevice.kt
- Library/src/main/java/dev/testify/core/DeviceIdentifier.kt
- Library/src/main/java/dev/testify/core/logic/AssertSame.kt
- Library/src/main/java/dev/testify/internal/helpers/OutputFileName.kt
- Library/src/test/java/dev/testify/ScreenshotRuleTest.kt
- Library/src/test/java/dev/testify/scenario/ScreenshotScenarioRuleTest.kt
Resolves #206 
In most situations the Test and Target context agree on the device metrics.
However, when the user changes properties of the Activity under test at runtime, such as the orientation of the Activity, the device metrics associated with the Target Context are changed but the Test Context metrics are not changed.
This means that it is important to use the appropriate context when generating the device key.
> [!WARNING]
> **Depends on #252** 
The primary change is to clarify which context (target or test) is required for some key functions.
> [!WARNING]
> 206: Fix UnexpectedDeviceException caused by incorrect Context usage
